- hosts: localhost
  tasks:

    - name: Create directory
      file: path=/etc/mysql/ssl state=directory

    - name: Generate CSR Key
      command: openssl req -sha1 -newkey rsa:2048 -subj '/C=MT/ST=Northern Region/L=Mosta/O=Cloudways Ltd./OU=IT/CN={{ ansible_fqdn }}' -days 730 -nodes \
        -keyout /etc/mysql/ssl/mysql-key.key -out /etc/mysql/ssl/mysql-csr.crt

    - name: Add RSA key
      command: openssl rsa -in /etc/mysql/ssl/mysql-key.key -out /etc/mysql/ssl/mysql-key.key

    - name: Create Cert key
      command: openssl x509 -sha1 -req -in /etc/mysql/ssl/mysql-csr.crt -days 730 -CA /etc/mysql/ssl/cloudways_ca.crt -CAkey /etc/mysql/ssl/cloudways_ca.key \
        -set_serial 01 -out /etc/mysql/ssl/mysql-ssl.crt

    - name: Ansible copy file to remote server
      copy:
        src: ~/ssl.cnf
        dest: /etc/mysql/conf.d/

    - name: Update host
      replace: dest=/etc/mysql/my.cnf regexp='127.0.0.1' replace={{ ansible_eth0.ipv4.address }}

    - name: Update host
      shell: mysql -e "use mysql; UPDATE user set Host='%' where User NOT IN ('root', 'debian-sys-maint', 'sensu');"

    - name: Restart MySQL
      service: name=mysql state=restarted enabled=true
